### ISSUE TITLE
[QE.go/ qe_nonpreq] nonprenex であるが，一番外側が限量子である場合の型エラー

### ISSUE THREAD

**Issue by ysdln0616** [hiwane/ganrac#42]
qe.go の関数 qe_nonpreq の
`fml = qeopt.qe_prenex(fml.(FofQ), cond)`

(650 行目くらい) で
> panic: interface conversion: *ganrac.AtomT is not ganrac.FofQ: missing method Fml

となりました。

エラーが発生した時に入力した問題

> vars(l0, k1r, a1, k1c1, a0, l1, k1c0);
> F_p_0 = all([k1r], (all([l1, l0], (a0*l1-a0*k1c1+a1*k1c0-a1*l0-l1*k1c0+l0*k1c1!=0 || l1^2-2*l1*k1c1+k1c0^2-2*k1c0*l0-k1r^2+l0^2+k1c1^2!=0 || a0*l1-a0*k1c1+a1*k1c0-a1*l0-l1*k1c0+l0*k1c1==0)) || k1r<=0));  
> qe(F_p_0); 

quantifier の再構築後、`fml` が True (False) であることが原因だったようです。修正よろしくお願いいたします。

**Comment by hiwane** [comment]
ありがとうございます。

いただいた入力だと synrac error になったので再現できませんでしたが、適当に修正してみました。
ご確認お願いします。
